#!/bin/bash
set -euo pipefail

# Auto-generate the source list from Sources/AISources/*.swift
SOURCES_FILE="Sources/GeneratedSourceList.swift"
echo "// Auto-generated by build.sh — do not edit manually." > "$SOURCES_FILE"
echo "// To add a new source, create a new file in Sources/AISources/." >> "$SOURCES_FILE"
echo "let allSources: [AISource] = [" >> "$SOURCES_FILE"
for f in Sources/AISources/*Source.swift; do
    [ "$(basename "$f")" = "AISource.swift" ] && continue
    struct_name=$(grep -o 'struct [A-Za-z_]*: AISource' "$f" | head -1 | awk '{print $2}' | cut -d: -f1)
    [ -n "$struct_name" ] && echo "    ${struct_name}()," >> "$SOURCES_FILE"
done
echo "]" >> "$SOURCES_FILE"

# If --test flag is passed, stop here (tests only need the generated source list)
if [ "${1:-}" = "--test" ]; then
    echo "Source list generated. Ready for testing."
    exit 0
fi

# Build release binary
swift build -c release

# Package app bundle
rm -rf Rashun.app
mkdir -p Rashun.app/Contents/{MacOS,Resources}
cp .build/release/Rashun Rashun.app/Contents/MacOS/Rashun
cp Info.plist Rashun.app/Contents/
cp AppIcon.icns Rashun.app/Contents/Resources/

# Code sign
codesign --force --deep --sign - --entitlements Rashun.entitlements Rashun.app

echo "Build complete: Rashun.app"

# If --open flag is passed, quit the running app (if any) and open the new build
if [ "${1:-}" = "--open" ]; then
    osascript -e 'quit app "Rashun"' 2>/dev/null || true
    sleep 0.5
    open Rashun.app
fi
