#!/bin/bash

# Auto-generate the source list from Sources/AISources/*.swift
SOURCES_FILE="Sources/GeneratedSourceList.swift"
echo "// Auto-generated by build.sh — do not edit manually." > "$SOURCES_FILE"
echo "// To add a new source, create a new file in Sources/AISources/." >> "$SOURCES_FILE"
echo "let allSources: [AISource] = [" >> "$SOURCES_FILE"
for f in Sources/AISources/*Source.swift; do
    [ "$(basename "$f")" = "AISource.swift" ] && continue
    struct_name=$(grep -o 'struct [A-Za-z_]*: AISource' "$f" | head -1 | awk '{print $2}' | cut -d: -f1)
    [ -n "$struct_name" ] && echo "    ${struct_name}()," >> "$SOURCES_FILE"
done
echo "]" >> "$SOURCES_FILE"

swift build -c release
rm -rf Rashun.app
mkdir -p Rashun.app/Contents/{MacOS,Resources}
cp .build/release/Rashun Rashun.app/Contents/MacOS/Rashun
cp Info.plist Rashun.app/Contents/ # (assuming you saved Info.plist in root)
# If you have an icon: cp AppIcon.icns Rashun.app/Contents/Resources/
# Re-sign the amp binary to avoid network volume alert when spawning it
codesign --force --sign - "$HOME/.amp/bin/amp" 2>/dev/null || true
codesign --force --deep --sign - --entitlements Rashun.entitlements Rashun.app
open Rashun.app