#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

SOURCE_DIR="Sources/RashunCore/AISources"
SOURCES_FILE="Sources/RashunCore/GeneratedSourceList.swift"

show_help() {
    cat <<'EOF'
Usage: ./build.sh [options]

Options:
  --test       Generate source list and run tests
  --open       On macOS, open the built Rashun.app after packaging
  --cli-only   Build only the CLI target
    --link-cli   Create/update a user-level 'rashun' command link (~/.local/bin)
  --help       Show this help text

Behavior:
  macOS default: build RashunCLI + Rashun app bundle
  Linux/Windows default: build RashunCLI only
EOF
}

RUN_TESTS=false
OPEN_APP=false
CLI_ONLY=false
LINK_CLI=false

for arg in "$@"; do
    case "$arg" in
        --test) RUN_TESTS=true ;;
        --open) OPEN_APP=true ;;
        --cli-only) CLI_ONLY=true ;;
        --link-cli) LINK_CLI=true ;;
        --help|-h)
            show_help
            exit 0
            ;;
        *)
            echo "Unknown option: $arg" >&2
            show_help >&2
            exit 2
            ;;
    esac
done

install_user_cli_link() {
    local target_bin="$1"
    local user_bin_dir="$HOME/.local/bin"
    local link_path="$user_bin_dir/rashun"

    mkdir -p "$user_bin_dir"
    ln -sfn "$target_bin" "$link_path"

    echo "CLI shortcut updated: $link_path -> $target_bin"
    case ":$PATH:" in
        *":$user_bin_dir:"*)
            echo "You can now run: rashun --help"
            ;;
        *)
            echo "Add ~/.local/bin to PATH to run 'rashun' globally:"
            echo "  echo 'export PATH=\"$HOME/.local/bin:$PATH\"' >> ~/.zshrc"
            echo "  source ~/.zshrc"
            ;;
    esac
}

if [ ! -d "$SOURCE_DIR" ]; then
    echo "Missing source directory: $SOURCE_DIR" >&2
    exit 1
fi

# Auto-generate the source list from Sources/RashunCore/AISources/*Source.swift
{
    echo "// Auto-generated by build.sh — do not edit manually."
    echo "// To add a new source, create a new file in Sources/RashunCore/AISources/."
    echo "public let allSources: [AISource] = ["
    for f in "$SOURCE_DIR"/*Source.swift; do
        [ "$(basename "$f")" = "AISource.swift" ] && continue
        struct_name=$(grep -Eo '([[:space:]]|^)public struct [A-Za-z_][A-Za-z0-9_]*: AISource|([[:space:]]|^)struct [A-Za-z_][A-Za-z0-9_]*: AISource' "$f" | head -1 | sed -E 's/.*struct ([A-Za-z_][A-Za-z0-9_]*) *: AISource.*/\1/')
        [ -n "$struct_name" ] && echo "    ${struct_name}(),"
    done
    echo "]"
} > "$SOURCES_FILE"

echo "Generated $SOURCES_FILE"

if [ "$RUN_TESTS" = true ]; then
    swift test
    exit 0
fi

is_macos=false
if [ "$(uname -s)" = "Darwin" ]; then
    is_macos=true
fi

if [ "$CLI_ONLY" = true ] || [ "$is_macos" = false ]; then
    swift build -c release --product RashunCLI
    BIN_DIR=$(swift build -c release --show-bin-path)
    if [ "$LINK_CLI" = true ]; then
        install_user_cli_link "$BIN_DIR/RashunCLI"
    fi
    echo "CLI build complete (RashunCLI)."
    exit 0
fi

# macOS full build: build app + CLI, then package Rashun.app
swift build -c release --product Rashun
swift build -c release --product RashunCLI
BIN_DIR=$(swift build -c release --show-bin-path)

rm -rf Rashun.app
mkdir -p Rashun.app/Contents/{MacOS,Resources}
cp "$BIN_DIR/Rashun" Rashun.app/Contents/MacOS/Rashun
cp "$BIN_DIR/RashunCLI" Rashun.app/Contents/MacOS/RashunCLI
cp Info.plist Rashun.app/Contents/

if [ -f AppIcon.icns ]; then
    cp AppIcon.icns Rashun.app/Contents/Resources/
fi

# Copy SwiftPM resource bundles into app resources.
find "$BIN_DIR" -maxdepth 1 -type d -name "*.bundle" -exec cp -R {} Rashun.app/Contents/Resources/ \;

# Code sign ad-hoc for local runs.
codesign --force --deep --sign - --entitlements Rashun.entitlements Rashun.app

echo "Build complete: Rashun.app"
if [ "$LINK_CLI" = true ] || [ "$OPEN_APP" = true ]; then
    install_user_cli_link "$BIN_DIR/RashunCLI"
fi
if [ "$OPEN_APP" = true ]; then
    osascript -e 'quit app "Rashun"' 2>/dev/null || true
    sleep 0.5
    open Rashun.app
fi
