// Auto-generated by build.sh — do not edit manually.
// To add a new source, create a new file in Sources/RashunCore/AISources/.
public let allSources: [AISource] = [
    AmpSource(),
    CodexSource(),
    CopilotSource(),
    GeminiSource(),
]
