// Auto-generated by CI — do not edit manually.
// Overwritten during release builds with the actual version number.
// The default value is used only for local development builds.
public let rashunVersion: String = "0.0.0"
